[default]
extend-ignore-identifiers-re = [
    # Ignore ENR (Ethereum Node Record) strings which are base64 encoded
    "enr:-.*",
    # Ignore enode URLs
    "enode://.*",
    # Ignore git commit hashes (hexadecimal strings)
    "[0-9a-f]{7,40}"
]

[default.extend-words]
# Ignore "Iy" which appears in base64 encoded ENR strings
Iy = "Iy"
# Ignore "Dout" which is a valid libp2p gossipsub parameter name
Dout = "Dout"
# Ignore "abd" which appears in git commit hashes
abd = "abd"

[files]
extend-exclude = ["pkg/ethereum/node/enr/enr_test.go"]
