comment: false
github_checks:
  annotations: false
ignore:
  - ".github"
  - "README.md"
  - "LICENSE"
  - "Makefile"
  - ".tool-versions"
  - "llms"
  - ".cursor"
  - "*.yaml"
  - "*.yml"
  - "**/*.pb.go"
  - "**/*.mock.go"
  - "**/*.pb.validate.go"
  - "pkg/testutil"
