name: 'Go Setup'
description: 'Sets up Go environment with caching'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25.1'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
